apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Values.app }}
  ports:
    - name: http       
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.target_port }}
    

